config/routes.rb
Rails.application.routes.draw do
  root :to => "movies#index", :director_id => '1'

  resources :directors, shallow: true, only: [:index, :show] do
    resources :movies, only: [:index, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :movies 
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :director
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  def index
    @directors = Director.all
  end

  def show
    @director = Director.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController 
  def index
    @director = Director.find(params[:director_id])
    @movies = @director.movies
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/directors/index.html.erb
<section class="director-index">
  <h1 class="all-directors">All Directors</h1>

  <% @directors.each do |director| %>
  <ul>
    <li class="director-show-link">More information about: <%= link_to director.name, director_path(director) %></li>
  </ul>
  <% end %>
</section>

app/views/directors/show.html.erb
<section class="director-show">
  <h2 class="each-director">Information about: <%= @director.name %></h2>

  <%= button_to "Movies by #{@director.name}", director_movies_path(@director), method: :get, class: 'director-index-button' %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SassWorkshop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<section class="movie-index">
  <h1 class="all-movies">All Movies for <%= @director.name %></h1>

  <% @movies.each do |movie| %>
    <h2 class="movie-show-link"><%= link_to movie.title, movie_path(movie) %></h2>
    <p class="movie-description"><%= movie.description %></p>
  <% end %>
</section>

app/views/movies/show.html.erb
<section class="movie-show">
  <h1 class="movie-title"><%= @movie.title %></h1>
  <h2 class="director-show-link">Director: <%= link_to @movie.director.name, director_path(@movie.director) %></h2>
  <p class="movie-description"><%= @movie.description %></p>
</section>

app/views/welcome/index.html.erb
 <section class="welcome-index">
   <h1 class="welcome">Welcome to Ilana Corson's Sass Workshop!</h1>
   <p class="all-directors-link">Navigate to <%= link_to "All Directors", directors_path %><p>
 </section>